// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
var PROJECT_REF = "amwfmlqvaranonhyvqbj";
var DIRECT_SUPABASE_URL = `https://${PROJECT_REF}.supabase.co`;
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  return configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]) ?? DIRECT_SUPABASE_URL;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("Supabase publishable key is not configured");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var notAuthenticated = {
  content: [{ type: "text", text: "Not authenticated." }],
  isError: true
};
function textResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }]
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
var STUDIO_BUCKET = "studio-images";
async function signedAssetUrl(supabase, storagePath) {
  if (!storagePath) return null;
  try {
    const { data } = await supabase.storage.from(STUDIO_BUCKET).createSignedUrl(storagePath, 60 * 60);
    return data?.signedUrl ?? null;
  } catch {
    return null;
  }
}

// src/lib/mcp/tools/get-session.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
var get_session_default = defineTool({
  name: "get_session",
  title: "Get session detail",
  description: "Read one of the signed-in user's sessions: its prompts (messages) and the assets generated in it.",
  inputSchema: {
    session_id: z.string().describe("The session id (uuid)."),
    include_urls: z.boolean().describe("Include a temporary signed download URL for each asset.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id, include_urls }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data: session, error: sessionError } = await supabase.from("sessions").select("id, title, active_model_key, active_preset_id, settings_json, created_at, updated_at").eq("id", session_id).maybeSingle();
    if (sessionError) return errorResult(sessionError.message);
    if (!session) return errorResult(`No session ${session_id} for this user.`);
    const [{ data: messages, error: messagesError }, { data: assets, error: assetsError }] = await Promise.all([
      supabase.from("messages").select("id, seq, role, message_type, prompt_text, created_at").eq("session_id", session_id).order("seq", { ascending: true }),
      supabase.from("assets").select("id, asset_type, model_key, storage_path, prompt_snapshot, metadata_json, created_at").eq("session_id", session_id).order("created_at", { ascending: false })
    ]);
    if (messagesError) return errorResult(messagesError.message);
    if (assetsError) return errorResult(assetsError.message);
    const rows = assets ?? [];
    const enriched = await Promise.all(
      rows.map(async (asset) => {
        const meta = asset.metadata_json ?? {};
        return {
          id: asset.id,
          asset_type: asset.asset_type,
          model_key: asset.model_key,
          width: meta.width ?? null,
          height: meta.height ?? null,
          aspect_ratio: meta.aspect_ratio ?? null,
          prompt: asset.prompt_snapshot,
          created_at: asset.created_at,
          url: include_urls ? await signedAssetUrl(supabase, asset.storage_path) : void 0
        };
      })
    );
    return textResult({ session, messages: messages ?? [], assets: enriched });
  }
});

// src/lib/mcp/tools/list-assets.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";

// src/lib/mcp/frankApi.ts
var FRANK_BASE = `${DIRECT_SUPABASE_URL}/functions/v1/frank-api`;
function assetSummary(asset) {
  return {
    id: asset.id,
    media_type: asset.media_type ?? "image",
    model: asset.model,
    width: asset.width ?? null,
    height: asset.height ?? null,
    aspect_ratio: asset.aspect_ratio ?? null,
    prompt: asset.prompt ?? null,
    session_id: asset.session_id ?? null,
    url: asset.preview_url || asset.remote_url || null
  };
}
async function frankFetch(ctx, path, init = {}) {
  const token = ctx?.getToken();
  const res = await fetch(`${FRANK_BASE}${path}`, {
    method: init.method ?? "GET",
    headers: {
      "Content-Type": "application/json",
      ...token ? { Authorization: `Bearer ${token}` } : {}
    },
    ...init.body === void 0 ? {} : { body: JSON.stringify(init.body) }
  });
  const text = await res.text();
  if (!res.ok) {
    let message = text;
    try {
      const parsed = JSON.parse(text);
      message = parsed.error?.message || text;
    } catch {
    }
    throw new Error(`Studio API ${res.status}: ${String(message).slice(0, 500)}`);
  }
  return JSON.parse(text || "{}");
}

// src/lib/mcp/tools/list-assets.ts
var list_assets_default = defineTool2({
  name: "list_assets",
  title: "List recent assets",
  description: "List the caller's recent studio images and videos with download URLs and asset ids \u2014 useful for picking an upscale source or re-sending a reference.",
  inputSchema: {
    session_id: z2.string().describe("Only assets from this session.").optional(),
    media: z2.enum(["image", "video"]).describe("Filter by media kind.").optional(),
    limit: z2.number().int().describe("How many assets to return (1-50). Defaults to 20.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id, media, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    const query = session_id ? `?session_id=${encodeURIComponent(session_id)}` : "";
    try {
      const data = await frankFetch(ctx, `/assets${query}`);
      const rows = (data.assets ?? []).filter((a) => media ? (a.media_type ?? "image") === media : true).slice(0, take);
      return textResult({ assets: rows.map(assetSummary) });
    } catch (err) {
      return errorResult(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/list-models.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_models_default = defineTool3({
  name: "list_studio_options",
  title: "List studio options",
  description: "Discovery call: the image, video and upscaler models available in the studio with their allowed aspect ratios and sizes, plus the prompt presets. Call this before generate_image or upscale_media to pick valid values.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    try {
      const data = await frankFetch(
        null,
        "/models"
      );
      const models = (data.models ?? []).filter((m) => !m.legacy);
      const shape = (m) => ({
        id: m.id,
        label: m.label,
        provider: m.provider,
        status: m.status,
        description: m.description ?? null,
        aspect_ratios: m.allowed_aspect_ratios ?? [],
        sizes: m.allowed_image_sizes ?? [],
        max_reference_images: m.max_reference_images ?? null
      });
      const isUpscale = (m) => m.capabilities?.upscale === true;
      const isVideo = (m) => m.capabilities?.video === true;
      return textResult({
        image_models: models.filter((m) => !isUpscale(m) && !isVideo(m)).map(shape),
        video_models: models.filter((m) => !isUpscale(m) && isVideo(m)).map(shape),
        upscale_models: models.filter(isUpscale).map(shape),
        prompt_presets: data.promptPresets ?? []
      });
    } catch (err) {
      return errorResult(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/list-presets.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_presets_default = defineTool4({
  name: "list_presets",
  title: "List prompt presets",
  description: "List the active prompt presets in the studio library, including their category and system prompt.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("presets").select("id, name, category, system_prompt, positive_rules, negative_rules, is_active").eq("is_active", true).order("name", { ascending: true });
    if (error) return errorResult(error.message);
    return textResult({ presets: data ?? [] });
  }
});

// src/lib/mcp/tools/list-sessions.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_sessions_default = defineTool5({
  name: "list_sessions",
  title: "List studio sessions",
  description: "List the signed-in user's generation sessions (newest first) with their title, active model and preset.",
  inputSchema: {
    limit: z3.number().int().describe("How many sessions to return (1-50).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sessions").select("id, title, active_model_key, active_preset_id, created_at, updated_at").order("updated_at", { ascending: false }).limit(take);
    if (error) return errorResult(error.message);
    return textResult({ sessions: data ?? [] });
  }
});

// src/lib/mcp/tools/submit-feedback.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var submit_feedback_default = defineTool6({
  name: "submit_feedback",
  title: "Submit feedback",
  description: "File a feedback item in the studio on behalf of the signed-in user.",
  inputSchema: {
    message: z4.string().describe("The feedback text."),
    page_path: z4.string().describe("Optional page or area the feedback is about.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ message, page_path }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const text = message.trim();
    if (!text) return errorResult("Feedback message cannot be empty.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("feedback_items").insert({
      user_id: ctx.getUserId(),
      message: text,
      page_path: page_path ?? "mcp",
      route_name: "mcp"
    }).select("id, created_at").maybeSingle();
    if (error) return errorResult(error.message);
    return textResult({ submitted: true, id: data?.id ?? null, created_at: data?.created_at ?? null });
  }
});

// src/lib/mcp/index.ts
var mcp = defineMcp({
  name: "frank-create",
  title: "frank Create",
  version: "0.1.0",
  instructions: "Tools for the art-ificial studio (frank Create). Read the signed-in user's generation sessions and assets, inspect the available image/video models and prompt presets, and file feedback. Generation itself happens in the app UI.",
  auth: auth.oauth.issuer({
    issuer: `${DIRECT_SUPABASE_URL}/auth/v1`,
    acceptedAudiences: "authenticated",
    jwksUri: `${DIRECT_SUPABASE_URL}/auth/v1/.well-known/jwks.json`
  }),
  tools: [
    list_sessions_default,
    get_session_default,
    list_assets_default,
    list_models_default,
    list_presets_default,
    submit_feedback_default
  ]
});
var mcp_default = mcp;

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
