// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
var PROJECT_REF = "amwfmlqvaranonhyvqbj";
var DIRECT_SUPABASE_URL = `https://${PROJECT_REF}.supabase.co`;
var notAuthenticated = {
  content: [{ type: "text", text: "Not authenticated." }],
  isError: true
};
function textResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }]
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/check-run.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/frankApi.ts
var FRANK_BASE = `${DIRECT_SUPABASE_URL}/functions/v1/frank-api`;
function assetSummary(asset) {
  return {
    id: asset.id,
    media_type: asset.media_type ?? "image",
    model: asset.model,
    width: asset.width ?? null,
    height: asset.height ?? null,
    aspect_ratio: asset.aspect_ratio ?? null,
    prompt: asset.prompt ?? null,
    session_id: asset.session_id ?? null,
    url: asset.preview_url || asset.remote_url || null
  };
}
async function frankFetch(ctx, path, init = {}) {
  const token = ctx?.getToken();
  const res = await fetch(`${FRANK_BASE}${path}`, {
    method: init.method ?? "GET",
    headers: {
      "Content-Type": "application/json",
      ...token ? { Authorization: `Bearer ${token}` } : {}
    },
    ...init.body === void 0 ? {} : { body: JSON.stringify(init.body) }
  });
  const text = await res.text();
  if (!res.ok) {
    let message = text;
    try {
      const parsed = JSON.parse(text);
      message = parsed.error?.message || text;
    } catch {
    }
    throw new Error(`Studio API ${res.status}: ${String(message).slice(0, 500)}`);
  }
  return JSON.parse(text || "{}");
}
async function pollRun(ctx, first, maxMs = 11e4) {
  let latest = first;
  const turnId = latest.turn?.id;
  if (!turnId || latest.status !== "running") return latest;
  const started = Date.now();
  let delay = 4e3;
  while (Date.now() - started < maxMs) {
    await new Promise((r) => setTimeout(r, delay));
    delay = Math.min(delay + 2e3, 1e4);
    try {
      latest = await frankFetch(ctx, "/inference/status", {
        method: "POST",
        body: { turn_id: turnId }
      });
    } catch {
      continue;
    }
    if (latest.status !== "running") return latest;
  }
  return { ...latest, timed_out: true };
}

// src/lib/mcp/tools/check-run.ts
var check_run_default = defineTool({
  name: "check_run",
  title: "Check a run",
  description: "Check a generation or upscale run by its turn_id and collect the finished files. Use this when generate_image or upscale_media returned status 'running'.",
  inputSchema: {
    turn_id: z.string().describe("The turn id returned by generate_image or upscale_media.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ turn_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    try {
      const result = await frankFetch(ctx, "/inference/status", {
        method: "POST",
        body: { turn_id }
      });
      if (result.status === "failed") {
        return errorResult(result.error?.message || "The run failed.");
      }
      return textResult({
        status: result.status ?? "running",
        turn_id,
        outputs: (result.assets ?? []).map(assetSummary)
      });
    } catch (err) {
      return errorResult(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/generate-image.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var generate_image_default = defineTool2({
  name: "generate_image",
  title: "Generate images",
  description: "Run an image generation in the studio exactly as the app does: a prompt, a model, aspect ratio, size, how many variations, and optional reference image URLs. Returns download URLs for the finished images. Use list_studio_options first for valid model ids, aspect ratios and sizes.",
  inputSchema: {
    prompt: z2.string().describe("The full image prompt / brief to render."),
    model: z2.string().describe("Model id from list_studio_options, e.g. 'nano-banana-pro'. Defaults to nano-banana-pro.").optional(),
    aspect_ratio: z2.string().describe("Aspect ratio such as '1:1', '3:4', '16:9'.").optional(),
    size: z2.string().describe("Size or quality tier the model allows, e.g. '1K', '2K', '1536x1024'.").optional(),
    count: z2.number().int().describe("How many variations to render (1-6).").optional(),
    reference_image_urls: z2.array(z2.string()).describe("Public https URLs of reference images to condition on.").optional(),
    session_id: z2.string().describe("Session to record the run in. Omit to use the caller's default session.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const prompt = input.prompt.trim();
    if (!prompt) return errorResult("A prompt is required.");
    const refs = (input.reference_image_urls ?? []).filter((u) => /^https?:\/\//i.test(u));
    try {
      const first = await frankFetch(ctx, "/inference/turn", {
        method: "POST",
        body: {
          session_id: input.session_id,
          kind: refs.length ? "edit" : "generate",
          model: input.model || "nano-banana-pro",
          prompt,
          frank_body_mode: false,
          settings: {
            aspect_ratio: input.aspect_ratio || "1:1",
            image_size: input.size || "",
            count: Math.min(Math.max(input.count ?? 1, 1), 6)
          },
          reference_asset_ids: [],
          reference_image_urls: refs
        }
      });
      const result = await pollRun(ctx, first);
      if (result.status === "failed" || result.status === "blocked") {
        return errorResult(result.error?.message || "The generation failed.");
      }
      if (result.timed_out) {
        return textResult({
          status: "running",
          turn_id: result.turn?.id ?? null,
          note: "Still rendering. Call check_run with this turn_id in a minute to collect the images."
        });
      }
      return textResult({
        status: result.status ?? "complete",
        turn_id: result.turn?.id ?? null,
        images: (result.assets ?? []).map(assetSummary)
      });
    } catch (err) {
      return errorResult(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/list-assets.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_assets_default = defineTool3({
  name: "list_assets",
  title: "List recent assets",
  description: "List the caller's recent studio images and videos with download URLs and asset ids \u2014 useful for picking an upscale source or re-sending a reference.",
  inputSchema: {
    session_id: z3.string().describe("Only assets from this session.").optional(),
    media: z3.enum(["image", "video"]).describe("Filter by media kind.").optional(),
    limit: z3.number().int().describe("How many assets to return (1-50). Defaults to 20.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id, media, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    const query = session_id ? `?session_id=${encodeURIComponent(session_id)}` : "";
    try {
      const data = await frankFetch(ctx, `/assets${query}`);
      const rows = (data.assets ?? []).filter((a) => media ? (a.media_type ?? "image") === media : true).slice(0, take);
      return textResult({ assets: rows.map(assetSummary) });
    } catch (err) {
      return errorResult(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/list-models.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_models_default = defineTool4({
  name: "list_studio_options",
  title: "List studio options",
  description: "Discovery call: the image, video and upscaler models available in the studio with their allowed aspect ratios and sizes, plus the prompt presets. Call this before generate_image or upscale_media to pick valid values.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    try {
      const data = await frankFetch(
        null,
        "/models"
      );
      const models = (data.models ?? []).filter((m) => !m.legacy);
      const shape = (m) => ({
        id: m.id,
        label: m.label,
        provider: m.provider,
        status: m.status,
        description: m.description ?? null,
        aspect_ratios: m.allowed_aspect_ratios ?? [],
        sizes: m.allowed_image_sizes ?? [],
        max_reference_images: m.max_reference_images ?? null
      });
      const isUpscale = (m) => m.capabilities?.upscale === true;
      const isVideo = (m) => m.capabilities?.video === true;
      return textResult({
        image_models: models.filter((m) => !isUpscale(m) && !isVideo(m)).map(shape),
        video_models: models.filter((m) => !isUpscale(m) && isVideo(m)).map(shape),
        upscale_models: models.filter(isUpscale).map(shape),
        prompt_presets: data.promptPresets ?? []
      });
    } catch (err) {
      return errorResult(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/upscale-media.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var upscale_media_default = defineTool5({
  name: "upscale_media",
  title: "Upscale an image or video",
  description: "Send an image or video to the studio's upscaler and get the enhanced file back. Source can be a public URL or an asset id from list_assets. Videos and 4x/6x image jobs can outlast the call \u2014 you then get a turn_id to poll with check_run.",
  inputSchema: {
    source_url: z4.string().describe("Public https URL of the image or video to upscale.").optional(),
    source_asset_id: z4.string().describe("Asset id from list_assets to upscale instead of a URL.").optional(),
    media: z4.enum(["image", "video"]).describe("Media kind. Defaults to image.").optional(),
    model: z4.string().describe("Upscale model id from list_studio_options. Defaults to topaz-image-upscale / topaz-video-upscale.").optional(),
    upscale_factor: z4.enum(["None", "2x", "4x", "6x"]).describe("Image upscale factor.").optional(),
    target_resolution: z4.enum(["720p", "1080p", "4k"]).describe("Video target resolution.").optional(),
    session_id: z4.string().describe("Session to record the run in.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    if (!input.source_url && !input.source_asset_id) {
      return errorResult("Provide source_url or source_asset_id.");
    }
    const media = input.media ?? "image";
    const model = input.model || (media === "video" ? "topaz-video-upscale" : "topaz-image-upscale");
    try {
      const first = await frankFetch(ctx, "/enhance", {
        method: "POST",
        body: {
          session_id: input.session_id,
          model,
          source_asset_id: input.source_asset_id,
          source_url: input.source_url,
          settings: {
            media,
            ...media === "image" ? { upscale_factor: input.upscale_factor ?? "2x", output_format: "png" } : { target_resolution: input.target_resolution ?? "1080p" }
          }
        }
      });
      const result = await pollRun(ctx, first);
      if (result.status === "failed" || result.status === "blocked") {
        return errorResult(result.error?.message || "The upscale failed.");
      }
      if (result.timed_out) {
        return textResult({
          status: "running",
          turn_id: result.turn?.id ?? null,
          note: "Still upscaling. Call check_run with this turn_id to collect the result."
        });
      }
      return textResult({
        status: result.status ?? "complete",
        turn_id: result.turn?.id ?? null,
        outputs: (result.assets ?? []).map(assetSummary)
      });
    } catch (err) {
      return errorResult(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/tools/write-prompt.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var write_prompt_default = defineTool6({
  name: "write_prompt",
  title: "Write a prompt (Prompt Generator)",
  description: "Run the studio's Prompt Generator on a brief and get the crafted image prompt back. Pass the whole conversation so far in `messages` to iterate. The result can be fed straight into generate_image.",
  inputSchema: {
    brief: z5.string().describe("The brief or instruction. Shortcut for a single user message.").optional(),
    messages: z5.array(
      z5.object({
        role: z5.enum(["user", "assistant"]),
        content: z5.string(),
        images: z5.array(z5.string()).optional()
      })
    ).describe("Full conversation so far (newest last). Use instead of `brief` for follow-ups.").optional(),
    reference_image_urls: z5.array(z5.string()).describe("Public https URLs of reference images to describe alongside the brief.").optional(),
    skill: z5.string().describe("Prompt Generator skill key, e.g. 'brief-to-prompt'. Defaults to brief-to-prompt.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const refs = (input.reference_image_urls ?? []).filter((u) => /^https?:\/\//i.test(u));
    const messages = input.messages?.length ? input.messages : input.brief?.trim() ? [{ role: "user", content: input.brief.trim() }] : [];
    if (!messages.length) return errorResult("Provide `brief` or `messages`.");
    if (refs.length) {
      const last = messages[messages.length - 1];
      messages[messages.length - 1] = { ...last, images: [...last.images ?? [], ...refs] };
    }
    try {
      const data = await frankFetch(
        ctx,
        "/prompt-agent",
        { method: "POST", body: { messages, skill: input.skill || "brief-to-prompt" } }
      );
      return textResult({ prompt: data.reply, model: data.model, skill: data.skill });
    } catch (err) {
      return errorResult(err instanceof Error ? err.message : String(err));
    }
  }
});

// src/lib/mcp/index.ts
var mcp = defineMcp({
  name: "frank-create",
  title: "frank Create",
  version: "0.2.0",
  instructions: "Tools for the art-ificial studio (frank Create). Turn a brief into a crafted prompt with write_prompt, render it with generate_image (check list_studio_options for model ids, aspect ratios and sizes), upscale images or videos with upscale_media, browse past outputs with list_assets, and poll long runs with check_run.",
  auth: auth.oauth.issuer({
    issuer: `${DIRECT_SUPABASE_URL}/auth/v1`,
    acceptedAudiences: "authenticated",
    jwksUri: `${DIRECT_SUPABASE_URL}/auth/v1/.well-known/jwks.json`
  }),
  tools: [
    list_models_default,
    write_prompt_default,
    generate_image_default,
    upscale_media_default,
    check_run_default,
    list_assets_default
  ]
});
var mcp_default = mcp;

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
