// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
var PROJECT_REF = "amwfmlqvaranonhyvqbj";
var DIRECT_SUPABASE_URL = `https://${PROJECT_REF}.supabase.co`;
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  return configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]) ?? DIRECT_SUPABASE_URL;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("Supabase publishable key is not configured");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var notAuthenticated = {
  content: [{ type: "text", text: "Not authenticated." }],
  isError: true
};
function textResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }]
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
var STUDIO_BUCKET = "studio-images";
async function signedAssetUrl(supabase, storagePath) {
  if (!storagePath) return null;
  try {
    const { data } = await supabase.storage.from(STUDIO_BUCKET).createSignedUrl(storagePath, 60 * 60);
    return data?.signedUrl ?? null;
  } catch {
    return null;
  }
}

// src/lib/mcp/tools/get-session.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
var get_session_default = defineTool({
  name: "get_session",
  title: "Get session detail",
  description: "Read one of the signed-in user's sessions: its prompts (messages) and the assets generated in it.",
  inputSchema: {
    session_id: z.string().describe("The session id (uuid)."),
    include_urls: z.boolean().describe("Include a temporary signed download URL for each asset.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id, include_urls }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data: session, error: sessionError } = await supabase.from("sessions").select("id, title, active_model_key, active_preset_id, settings_json, created_at, updated_at").eq("id", session_id).maybeSingle();
    if (sessionError) return errorResult(sessionError.message);
    if (!session) return errorResult(`No session ${session_id} for this user.`);
    const [{ data: messages, error: messagesError }, { data: assets, error: assetsError }] = await Promise.all([
      supabase.from("messages").select("id, seq, role, message_type, prompt_text, created_at").eq("session_id", session_id).order("seq", { ascending: true }),
      supabase.from("assets").select("id, asset_type, model_key, storage_path, prompt_snapshot, metadata_json, created_at").eq("session_id", session_id).order("created_at", { ascending: false })
    ]);
    if (messagesError) return errorResult(messagesError.message);
    if (assetsError) return errorResult(assetsError.message);
    const rows = assets ?? [];
    const enriched = await Promise.all(
      rows.map(async (asset) => {
        const meta = asset.metadata_json ?? {};
        return {
          id: asset.id,
          asset_type: asset.asset_type,
          model_key: asset.model_key,
          approval_status: meta.approval_status ?? "none",
          width: meta.width ?? null,
          height: meta.height ?? null,
          aspect_ratio: meta.aspect_ratio ?? null,
          prompt: asset.prompt_snapshot,
          created_at: asset.created_at,
          url: include_urls ? await signedAssetUrl(supabase, asset.storage_path) : void 0
        };
      })
    );
    return textResult({ session, messages: messages ?? [], assets: enriched });
  }
});

// src/lib/mcp/tools/list-assets.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_assets_default = defineTool2({
  name: "list_assets",
  title: "List generated assets",
  description: "List the signed-in user's generated images and videos, newest first, optionally filtered by session, media type or approval status.",
  inputSchema: {
    session_id: z2.string().describe("Only assets from this session id.").optional(),
    asset_type: z2.enum(["image", "video"]).describe("Filter by media type.").optional(),
    approval_status: z2.enum(["approved", "rejected", "review", "any"]).describe("Filter by approval status. Defaults to any.").optional(),
    limit: z2.number().int().describe("How many assets to return (1-50).").optional(),
    include_urls: z2.boolean().describe("Include temporary signed download URLs.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id, asset_type, approval_status, limit, include_urls }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("assets").select("id, session_id, asset_type, model_key, storage_path, prompt_snapshot, metadata_json, created_at").order("created_at", { ascending: false }).limit(take);
    if (session_id) query = query.eq("session_id", session_id);
    if (asset_type) query = query.eq("asset_type", asset_type);
    if (approval_status && approval_status !== "any") {
      query = query.eq("metadata_json->>approval_status", approval_status);
    }
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    const assets = await Promise.all(
      (data ?? []).map(async (asset) => {
        const meta = asset.metadata_json ?? {};
        return {
          id: asset.id,
          session_id: asset.session_id,
          asset_type: asset.asset_type,
          model_key: asset.model_key,
          approval_status: meta.approval_status ?? "none",
          width: meta.width ?? null,
          height: meta.height ?? null,
          aspect_ratio: meta.aspect_ratio ?? null,
          prompt: asset.prompt_snapshot,
          created_at: asset.created_at,
          url: include_urls ? await signedAssetUrl(supabase, asset.storage_path) : void 0
        };
      })
    );
    return textResult({ assets });
  }
});

// src/lib/mcp/tools/list-models.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_models_default = defineTool3({
  name: "list_models",
  title: "List generation models",
  description: "List the image and video models available in the studio with their supported aspect ratios, resolutions and reference-image limits.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("model_capabilities").select(
      "model_key, provider, label, blurb, supports_editing, supports_multi_reference, max_reference_images, supported_aspect_ratios, supported_resolutions"
    ).order("model_key", { ascending: true });
    if (error) return errorResult(error.message);
    return textResult({ models: data ?? [] });
  }
});

// src/lib/mcp/tools/list-presets.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_presets_default = defineTool4({
  name: "list_presets",
  title: "List prompt presets",
  description: "List the active prompt presets in the studio library, including their category and system prompt.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("presets").select("id, name, category, system_prompt, positive_rules, negative_rules, is_active").eq("is_active", true).order("name", { ascending: true });
    if (error) return errorResult(error.message);
    return textResult({ presets: data ?? [] });
  }
});

// src/lib/mcp/tools/list-sessions.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_sessions_default = defineTool5({
  name: "list_sessions",
  title: "List studio sessions",
  description: "List the signed-in user's generation sessions (newest first) with their title, active model and preset.",
  inputSchema: {
    limit: z3.number().int().describe("How many sessions to return (1-50).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sessions").select("id, title, active_model_key, active_preset_id, created_at, updated_at").order("updated_at", { ascending: false }).limit(take);
    if (error) return errorResult(error.message);
    return textResult({ sessions: data ?? [] });
  }
});

// src/lib/mcp/tools/submit-feedback.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var submit_feedback_default = defineTool6({
  name: "submit_feedback",
  title: "Submit feedback",
  description: "File a feedback item in the studio on behalf of the signed-in user.",
  inputSchema: {
    message: z4.string().describe("The feedback text."),
    page_path: z4.string().describe("Optional page or area the feedback is about.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ message, page_path }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const text = message.trim();
    if (!text) return errorResult("Feedback message cannot be empty.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("feedback_items").insert({
      user_id: ctx.getUserId(),
      message: text,
      page_path: page_path ?? "mcp",
      route_name: "mcp"
    }).select("id, created_at").maybeSingle();
    if (error) return errorResult(error.message);
    return textResult({ submitted: true, id: data?.id ?? null, created_at: data?.created_at ?? null });
  }
});

// src/lib/mcp/index.ts
var mcp = defineMcp({
  name: "frank-create",
  title: "frank Create",
  version: "0.1.0",
  instructions: "Tools for the art-ificial studio (frank Create). Read the signed-in user's generation sessions and assets, approve or reject assets, inspect the available image/video models and prompt presets, and file feedback. Generation itself happens in the app UI.",
  auth: auth.oauth.issuer({
    issuer: `${DIRECT_SUPABASE_URL}/auth/v1`,
    acceptedAudiences: "authenticated",
    jwksUri: `${DIRECT_SUPABASE_URL}/auth/v1/.well-known/jwks.json`
  }),
  tools: [
    list_sessions_default,
    get_session_default,
    list_assets_default,
    list_models_default,
    list_presets_default,
    submit_feedback_default
  ]
});
var mcp_default = mcp;

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
