import type { BrandKit, FrankConfig } from "./types";

export const fallbackBrandKit: BrandKit = {
  style_guidance:
    "Warm off-white, Frank pink, cherry red, coffee brown, and off-black palette. Cheeky but director-ready body-care attitude. Tactile coffee/body-scrub textures, glossy skin-care detail, warm flash, editorial realism, and packaging that stays clean.",
  negative_prompt:
    "Avoid warped logos, extra lids, plastic skin, over-airbrushed bodies, muddy coffee spills, generic beige spa stock-photo styling, and unreadable packaging labels.",
  reference_notes:
    "Use approved Frank Body pack shots first, then lifestyle/body-care references. Keep source product identity more important than style experiments.",
  sync_status: "local",
  remote_id: null
};

export const fallbackConfig: FrankConfig = {
  tasks: [
    {
      key: "product-shot-lab",
      label: "Product Shot Lab",
      description: "Upload product/reference images, generate variants, approve, and export.",
      providers: ["google", "replicate", "openai"]
    },
    {
      key: "background-remove",
      label: "Background sweep",
      description: "Transparent PNGs and clean product isolation.",
      providers: ["openai"]
    },
    {
      key: "background-replace",
      label: "Background glow-up",
      description: "Frank-branded lifestyle and campaign backdrops.",
      providers: ["google", "openai"]
    },
    {
      key: "product-cleanup",
      label: "Product polish",
      description: "Retouch labels, dust, shadows, and product edges.",
      providers: ["openai"]
    },
    {
      key: "campaign-variants",
      label: "Campaign remix",
      description: "Creative rounds from one approved product direction.",
      providers: ["google", "openai", "replicate"]
    },
    {
      key: "aspect-crops",
      label: "Crop the goods",
      description: "PDP, email, feed, story, and paid-social crops.",
      providers: ["google", "replicate"]
    },
    {
      key: "upscale-enhance",
      label: "Make it bigger",
      description: "High-res masters with product detail intact.",
      providers: ["openai"]
    },
    {
      key: "prompt-remix",
      label: "Brief remix",
      description: "Sharper directions before another creative round.",
      providers: ["openai", "google"]
    }
  ],
  providers: [
    { key: "openrouter", label: "OpenRouter", type: "api", status: "curated" },
    { key: "google", label: "Gemini / Nano Banana", type: "api", status: "curated" },
    { key: "replicate", label: "Replicate", type: "api", status: "curated" },
    { key: "openai", label: "OpenAI image/edit", type: "api", status: "curated" }
  ],

  models: [
    {
      id: "google-nb-pro",
      label: "Gemini 3 Pro Image / Nano Banana Pro",
      short_label: "Nano Banana Pro",
      provider: "openrouter",
      provider_model: "google/gemini-3-pro-image",
      status: "ready",
      badge: "4K",
      max_resolution_label: "4K",
      description: "Nano Banana Pro (Gemini 3 Pro Image) via OpenRouter — 1K / 2K / 4K, wide aspect enum, up to 14 reference images.",
      capabilities: { generation: true, edit: true, masked_edit: false, video: false },
      allowed_aspect_ratios: [
        "1:1", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4", "9:16", "16:9", "21:9"
      ],
      allowed_image_sizes: ["1K", "2K", "4K"],
      reference_image_limit: 14,
      max_count: 4,
      cost_label: "premium",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "google-nb-2",
      label: "Gemini 3.1 Flash Image / Nano Banana 2",
      short_label: "Nano Banana 2",
      provider: "openrouter",
      provider_model: "google/gemini-3.1-flash-image",
      status: "ready",
      badge: "4K",
      max_resolution_label: "4K",
      description: "Nano Banana 2 (Gemini 3.1 Flash Image) via OpenRouter — fast 1K / 2K / 4K generation and editing, up to 14 refs.",
      capabilities: { generation: true, edit: true, masked_edit: false, video: false },
      allowed_aspect_ratios: [
        "1:1", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4", "9:16", "16:9", "21:9"
      ],
      allowed_image_sizes: ["1K", "2K", "4K"],
      reference_image_limit: 14,
      max_count: 4,
      cost_label: "fast",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "openai-gpt-image-2",
      label: "OpenAI gpt-image-2",
      short_label: "gpt-image-2",
      provider: "openrouter",
      provider_model: "openai/gpt-image-2",
      status: "ready",
      badge: "2K",
      max_resolution_label: "2K",
      description: "OpenAI gpt-image-2 via OpenRouter — strongest text rendering and instruction following, native batches up to 10.",
      capabilities: { generation: true, edit: true, masked_edit: true, video: false },
      allowed_aspect_ratios: ["1:1", "3:2", "2:3", "4:3", "3:4", "16:9", "9:16"],
      allowed_image_sizes: ["1K", "2K"],
      reference_image_limit: 10,
      max_count: 10,
      cost_label: "premium",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "seedream-5-pro",
      label: "Seedream 5.0 Pro (ByteDance)",
      short_label: "Seedream 5.0 Pro",
      provider: "openrouter",
      provider_model: "bytedance-seed/seedream-5-0-pro",
      status: "ready",
      badge: "4K",
      max_resolution_label: "4K",
      description: "ByteDance Seedream 5.0 Pro via OpenRouter — precise editing control, lifelike commercial scenes, native multi-image batches.",
      capabilities: { generation: true, edit: true, masked_edit: false, video: false },
      allowed_aspect_ratios: ["1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3", "21:9"],
      allowed_image_sizes: ["2K", "4K"],
      reference_image_limit: 10,
      max_count: 6,
      cost_label: "premium",
      configured: true,
      missing_env_vars: []
    },
    {
      // Superseded by Seedream 5.0 Pro. Kept in the roster (hidden from the
      // pickers) so historical rounds still resolve their real model label.
      id: "seedream-4-5",
      label: "Seedream 4.5 (ByteDance)",
      short_label: "Seedream 4.5",
      provider: "openrouter",
      provider_model: "bytedance-seed/seedream-4.5",
      status: "ready",
      legacy: true,
      badge: "4K",
      max_resolution_label: "4K",
      description: "ByteDance Seedream 4.5 via OpenRouter — photoreal product and campaign imagery, native multi-image batches.",
      capabilities: { generation: true, edit: true, masked_edit: false, video: false },
      allowed_aspect_ratios: ["1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3", "21:9"],
      allowed_image_sizes: ["2K", "4K"],
      reference_image_limit: 10,
      max_count: 6,
      cost_label: "premium",
      configured: true,
      missing_env_vars: []
    },

    {
      id: "flux-2-pro",
      label: "FLUX.2 Pro (Black Forest Labs)",
      short_label: "FLUX.2 Pro",
      provider: "openrouter",
      provider_model: "black-forest-labs/flux.2-pro",
      status: "ready",
      badge: "4K",
      max_resolution_label: "4K",
      description: "FLUX.2 Pro via OpenRouter — crisp detail and reliable composition control for hero and packaging shots.",
      capabilities: { generation: true, edit: true, masked_edit: false, video: false },
      allowed_aspect_ratios: ["1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3", "21:9"],
      allowed_image_sizes: ["1K", "2K", "4K"],
      reference_image_limit: 8,
      max_count: 4,
      cost_label: "premium",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "flux-2-max",
      label: "FLUX.2 Max (Black Forest Labs)",
      short_label: "FLUX.2 Max",
      provider: "openrouter",
      provider_model: "black-forest-labs/flux.2-max",
      status: "ready",
      badge: "4K",
      max_resolution_label: "4K",
      description: "FLUX.2 Max via OpenRouter — the highest-fidelity FLUX tier for finished campaign frames.",
      capabilities: { generation: true, edit: true, masked_edit: false, video: false },
      allowed_aspect_ratios: ["1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3", "21:9"],
      allowed_image_sizes: ["1K", "2K", "4K"],
      reference_image_limit: 8,
      max_count: 4,
      cost_label: "premium",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "riverflow-2-5-pro",
      label: "Riverflow 2.5 Pro (Sourceful)",
      short_label: "Riverflow 2.5 Pro",
      provider: "openrouter",
      provider_model: "sourceful/riverflow-v2.5-pro",
      status: "ready",
      badge: "4K",
      max_resolution_label: "4K",
      description: "Sourceful Riverflow 2.5 Pro via OpenRouter — agentic generation with the strongest text and typography control.",
      capabilities: { generation: true, edit: true, masked_edit: false, video: false },
      allowed_aspect_ratios: ["21:9", "16:9", "3:2", "4:3", "5:4", "1:1", "4:5", "3:4", "2:3", "9:16"],
      allowed_image_sizes: ["1K", "2K", "4K"],
      reference_image_limit: 10,
      max_count: 4,
      cost_label: "premium",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "qwen-image-3-pro",
      label: "Qwen Image 3 Pro (Alibaba)",
      short_label: "Qwen Image 3 Pro",
      provider: "openrouter",
      provider_model: "qwen/qwen-image-3-pro",
      status: "ready",
      badge: "2K",
      max_resolution_label: "2K",
      description: "Qwen Image 3 Pro via OpenRouter — strong bilingual text rendering and layout-aware composition.",
      capabilities: { generation: true, edit: true, masked_edit: false, video: false },
      allowed_aspect_ratios: ["1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3"],
      allowed_image_sizes: ["1K", "2K"],
      reference_image_limit: 6,
      max_count: 4,
      cost_label: "standard",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "krea-2-large",
      label: "Krea 2 Large",
      short_label: "Krea 2 Large",
      provider: "openrouter",
      provider_model: "krea/krea-2-large",
      status: "ready",
      badge: "2K",
      max_resolution_label: "2K",
      description: "Krea 2 Large via OpenRouter — distinctive art direction and texture for editorial and mood work.",
      capabilities: { generation: true, edit: true, masked_edit: false, video: false },
      allowed_aspect_ratios: ["1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3"],
      allowed_image_sizes: ["1K", "2K"],
      reference_image_limit: 6,
      max_count: 4,
      cost_label: "standard",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "mai-image-2-5-pro",
      label: "MAI-Image-2.5 Pro (Microsoft)",
      short_label: "MAI 2.5 Pro",
      provider: "openrouter",
      provider_model: "microsoft/mai-image-2.5-pro",
      status: "ready",
      badge: "2K",
      max_resolution_label: "2K",
      description: "Microsoft MAI-Image-2.5 Pro via OpenRouter — now publicly available, clean commercial-grade renders.",
      capabilities: { generation: true, edit: true, masked_edit: false, video: false },
      allowed_aspect_ratios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
      allowed_image_sizes: ["1K", "2K"],
      reference_image_limit: 6,
      max_count: 4,
      cost_label: "premium",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "grok-imagine-image",
      label: "Grok Imagine Image (xAI)",
      short_label: "Grok Imagine",
      provider: "openrouter",
      provider_model: "x-ai/grok-imagine-image-quality",
      status: "ready",
      badge: "2K",
      max_resolution_label: "2K",
      description: "xAI Grok Imagine (quality tier) via OpenRouter — fast, cheap ideation frames and rough boards.",
      capabilities: { generation: true, edit: true, masked_edit: false, video: false },
      allowed_aspect_ratios: ["1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3"],
      allowed_image_sizes: ["1K", "2K"],
      reference_image_limit: 4,
      max_count: 4,
      cost_label: "fast",
      configured: true,
      missing_env_vars: []
    },

    {
      id: "grok-imagine-video",
      label: "Grok Imagine Video",
      short_label: "Grok Imagine",
      provider: "openrouter",
      provider_model: "x-ai/grok-imagine-video",
      media: "video",
      status: "ready",
      badge: "720p",
      max_resolution_label: "720p",
      description: "xAI Grok Imagine Video via OpenRouter — cheapest of the roster. Text-to-video or image-to-video, 1–15s at 480p / 720p.",
      capabilities: { generation: true, edit: false, masked_edit: false, video: true },
      allowed_aspect_ratios: ["16:9", "9:16", "1:1", "4:3", "3:4", "3:2", "2:3"],
      allowed_image_sizes: [],
      allowed_durations: [3, 5, 8, 10, 15],
      allowed_resolutions: ["480p", "720p"],
      reference_image_limit: 1,
      max_count: 1,
      cost_label: "cheapest",
      price_per_second: 0.05,
      price_tier: "cheapest",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "dreamina-seedance-2",
      label: "Dreamina Seedance 2.0 (ByteDance)",
      short_label: "Seedance 2.0",
      provider: "openrouter",
      provider_model: "bytedance/seedance-2.0",
      media: "video",
      status: "ready",
      badge: "4K",
      max_resolution_label: "4K",
      description: "ByteDance Seedance 2.0 via OpenRouter — native audio, 480p → 4K, 4–15s, first/last frame plus reference images. Billed per output second by resolution.",
      capabilities: { generation: true, edit: false, masked_edit: false, video: true },
      allowed_aspect_ratios: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9", "9:21"],
      allowed_image_sizes: [],
      allowed_durations: [4, 5, 7, 10, 12, 15],
      allowed_resolutions: ["480p", "720p", "1080p", "4k"],
      supports_last_frame: true,
      reference_image_limit: 9,
      max_count: 1,
      cost_label: "premium",
      price_per_second_by_resolution: { "480p": 0.08, "720p": 0.18, "1080p": 0.45, "4k": 1.0 },
      price_tier: "standard",
      configured: true,
      missing_env_vars: []
    },
    {

      id: "seedance-2-5",
      label: "Seedance 2.5 (ByteDance)",
      short_label: "Seedance 2.5",
      provider: "openrouter",
      provider_model: "bytedance/seedance-2.5",
      media: "video",
      status: "ready",
      badge: "720p",
      max_resolution_label: "720p",
      description: "ByteDance Seedance 2.5 via OpenRouter — long-form storytelling up to 30s with native audio, first/last frame control and multimodal references. 480p / 720p.",
      capabilities: { generation: true, edit: false, masked_edit: false, video: true },
      allowed_aspect_ratios: ["16:9", "4:3", "1:1", "3:4", "9:16", "21:9"],
      allowed_image_sizes: [],
      allowed_durations: [4, 6, 8, 10, 12, 15, 20, 25, 30],
      allowed_resolutions: ["480p", "720p"],
      supports_last_frame: true,
      reference_image_limit: 9,
      max_count: 1,
      cost_label: "premium",
      price_per_second_by_resolution: { "480p": 0.12, "720p": 0.27 },
      price_tier: "standard",
      configured: true,
      missing_env_vars: []
    },

    {
      id: "grok-imagine-video-1-5",
      label: "Grok Imagine Video 1.5",
      short_label: "Grok 1.5",
      provider: "openrouter",
      provider_model: "x-ai/grok-imagine-video-1.5",
      media: "video",
      status: "ready",
      badge: "1080p",
      max_resolution_label: "1080p",
      description: "xAI Grok Imagine Video 1.5 via OpenRouter — image-to-video with synchronized audio. Needs a source frame. 1–15s up to 1080p.",
      capabilities: { generation: true, edit: false, masked_edit: false, video: true },
      allowed_aspect_ratios: ["16:9", "9:16", "1:1", "4:3", "3:4", "3:2", "2:3"],
      allowed_image_sizes: [],
      allowed_durations: [3, 5, 8, 10, 15],
      allowed_resolutions: ["480p", "720p", "1080p"],
      requires_source_image: true,
      reference_image_limit: 1,
      max_count: 1,
      cost_label: "premium",
      price_per_second: 0.08,
      price_tier: "standard",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "happyhorse-1-0",
      label: "Happy Horse 1.0 (Alibaba)",
      short_label: "Happy Horse",
      provider: "openrouter",
      provider_model: "alibaba/happyhorse-1.0",
      media: "video",
      status: "ready",
      badge: "1080p",
      max_resolution_label: "1080p",
      description: "Alibaba Happy Horse 1.0 via OpenRouter — text-to-video or single-image animation, 3–15s at 720p / 1080p.",
      capabilities: { generation: true, edit: false, masked_edit: false, video: true },
      allowed_aspect_ratios: ["16:9", "9:16", "1:1", "4:3", "3:4", "21:9", "9:21"],
      allowed_image_sizes: [],
      allowed_durations: [3, 5, 8, 10, 15],
      allowed_resolutions: ["720p", "1080p"],
      reference_image_limit: 1,
      max_count: 1,
      cost_label: "premium",
      price_per_second: 0.05,
      price_max_per_second: 0.11,
      price_tier: "standard",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "wan-2-7-i2v",
      label: "Wan 2.7 (image-to-video)",
      short_label: "Wan 2.7",
      provider: "openrouter",
      provider_model: "alibaba/wan-2.7",
      media: "video",
      status: "ready",
      badge: "1080p",
      max_resolution_label: "1080p",
      description: "Alibaba Wan 2.7 via OpenRouter — first/last frame control with synchronized audio. 2–10s at 720p / 1080p, explicit aspect ratios.",
      capabilities: { generation: true, edit: false, masked_edit: false, video: true },
      allowed_aspect_ratios: ["16:9", "9:16", "1:1", "4:3", "3:4"],
      allowed_image_sizes: [],
      allowed_durations: [2, 4, 6, 8, 10],
      allowed_resolutions: ["720p", "1080p"],
      requires_source_image: true,
      supports_last_frame: true,
      reference_image_limit: 2,
      max_count: 1,
      cost_label: "premium",
      price_per_second: 0.05,
      price_max_per_second: 0.11,
      price_tier: "standard",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "hailuo-2-3",
      label: "Minimax Hailuo 2.3",
      short_label: "Hailuo 2.3",
      provider: "openrouter",
      provider_model: "minimax/hailuo-2.3",
      media: "video",
      status: "ready",
      badge: "1080p",
      max_resolution_label: "1080p",
      description: "Minimax Hailuo 2.3 via OpenRouter — most expensive, best realistic human motion and cinematic VFX. 6s or 10s, 1080p 16:9 only.",
      capabilities: { generation: true, edit: false, masked_edit: false, video: true },
      allowed_aspect_ratios: ["16:9"],
      allowed_image_sizes: [],
      allowed_durations: [6, 10],
      allowed_resolutions: ["1080p"],
      reference_image_limit: 1,
      max_count: 1,
      cost_label: "premium",
      price_per_second: 0.08,
      price_tier: "premium",
      configured: true,
      missing_env_vars: []
    },


    // ---- Enhancer roster (upscalers, Enhancer tab only) ----
    {
      id: "recraft-crisp-upscale",
      label: "Recraft Crisp Upscale",
      short_label: "Crisp Upscale",
      provider: "replicate",
      provider_model: "recraft-ai/recraft-crisp-upscale",
      media: "image",
      status: "ready",
      badge: "FAST",
      max_resolution_label: "2x crisp",
      description: "Recraft Crisp Upscale (Replicate) — one-click sharpen and clean-up for web or print. No settings, fastest option.",
      capabilities: { generation: false, edit: true, masked_edit: false, video: false, upscale: true },
      allowed_aspect_ratios: [],
      allowed_image_sizes: [],
      upscale_controls: [],
      reference_image_limit: 1,
      max_count: 1,
      cost_label: "cheapest",
      price_tier: "cheapest",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "topaz-image-upscale",
      label: "Topaz Image Upscale",
      short_label: "Topaz Image",
      provider: "replicate",
      provider_model: "topazlabs/image-upscale",
      media: "image",
      status: "ready",
      badge: "6x",
      max_resolution_label: "up to 6x",
      description: "Topaz Labs image upscaler (Replicate) — pick an enhance model, up to 6x, subject detection, and optional face enhancement.",
      capabilities: { generation: false, edit: true, masked_edit: false, video: false, upscale: true },
      allowed_aspect_ratios: [],
      allowed_image_sizes: [],
      upscale_controls: ["enhance_model", "upscale_factor", "subject_detection", "output_format", "face_enhancement"],
      allowed_enhance_models: ["Standard V2", "Low Resolution V2", "CGI", "High Fidelity V2", "Text Refine"],
      allowed_upscale_factors: ["None", "2x", "4x", "6x"],
      allowed_subject_detections: ["None", "All", "Foreground", "Background"],
      allowed_output_formats: ["jpg", "png"],
      reference_image_limit: 1,
      max_count: 1,
      cost_label: "premium",
      price_tier: "standard",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "topaz-video-upscale",
      label: "Topaz Video Upscale",
      short_label: "Topaz Video",
      provider: "replicate",
      provider_model: "topazlabs/video-upscale",
      media: "video",
      status: "ready",
      badge: "4K",
      max_resolution_label: "4K",
      description: "Topaz Labs video upscaler (Replicate) — 720p / 1080p / 4K targets with frame interpolation up to 120fps. Long runs (minutes).",
      capabilities: { generation: false, edit: true, masked_edit: false, video: true, upscale: true },
      allowed_aspect_ratios: [],
      allowed_image_sizes: [],
      allowed_resolutions: ["720p", "1080p", "4k"],
      upscale_controls: ["target_resolution", "target_fps"],
      allowed_target_fps: [15, 24, 30, 48, 60, 120],
      requires_source_image: true,
      reference_image_limit: 1,
      max_count: 1,
      cost_label: "premium",
      price_tier: "premium",
      configured: true,
      missing_env_vars: []
    },
    {
      id: "crystal-video-upscaler",
      label: "Crystal Video Upscaler",
      short_label: "Crystal Video",
      provider: "replicate",
      provider_model: "philz1337x/crystal-video-upscaler",
      media: "video",
      status: "ready",
      badge: "4K cap",
      max_resolution_label: "4K cap",
      description: "Clarity AI Crystal video upscaler (Replicate) — free scale factor, tuned for portraits, faces, and products. Output is capped at 4K.",
      capabilities: { generation: false, edit: true, masked_edit: false, video: true, upscale: true },
      allowed_aspect_ratios: [],
      allowed_image_sizes: [],
      upscale_controls: ["scale_factor"],
      scale_factor_min: 1,
      scale_factor_max: 8,
      requires_source_image: true,
      reference_image_limit: 1,
      max_count: 1,
      cost_label: "premium",
      price_tier: "premium",
      configured: true,
      missing_env_vars: []
    }


  ],

  backlogModels: [],
  promptPresets: [
    {
      key: "product-shot-lab",
      label: "🧪 Product Shot Lab",
      description: "Clean product image for PDP, retouching, and channel crops.",
      prompt:
        "Frank Body [PRODUCT NAME] product-first composition. Clean label facing camera, honest skin-care texture, Frank pink accent, channel-ready negative space. Studio photography, soft realistic shadow, high-conversion PDP finish. 4K, photorealistic."
    },
    {
      key: "clean-ecom",
      label: "🛒 Clean Ecom",
      description: "Crisp commerce frame with readable packaging.",
      prompt:
        "Frank Body [PRODUCT NAME] product hero image for e-commerce PDP. High-gloss plastic packaging, centred in frame, clean white or soft off-white background, soft box lighting, no harsh shadows, full product visible, label legible. Studio photography style. 4K, photorealistic. Professional beauty brand e-commerce standard. No props, no model, no hands."
    },
    {
      key: "fb-lifestyle",
      label: "📸 FB Lifestyle",
      description: "Warm editorial lifestyle moment.",
      prompt:
        "Frank Body [PRODUCT NAME] warm editorial lifestyle image. Human skin or product-only flat lay — specify which. Warm natural light, bathroom or bedroom setting or marble surface. Product as supporting element or hero. Dried botanicals, minimal props. Vogue Beauty editorial feel, warm cream and terracotta tones. 4K, photorealistic."
    },
    {
      key: "fb-model-image",
      label: "👤 FB Model Image",
      description: "Campaign hero with a real body-care model moment.",
      prompt:
        "Frank Body campaign hero. Young woman, radiant glowing skin, applying or holding [PRODUCT NAME], warm natural light, beauty editorial mood. Authentic skin texture — not AI-smooth. Inclusive casting, confident body-care moment, warm direct flash, tactile product use, no plastic retouching. 4K, photorealistic."
    },
    {
      key: "campaign-variants",
      label: "🎯 Campaign Variants",
      description: "Creative rounds from one approved product direction.",
      prompt:
        "Frank Body [PRODUCT NAME] campaign variant. Keep product recognizable and label clean, push set styling, leave channel-ready headline space in the composition. Sharpen the Frank Body attitude — cheeky, warm, director-ready. Editorial realism, warm flash, tactile surfaces. 4K, photorealistic."
    },
    {
      key: "product-texture",
      label: "🧴 Product Texture",
      description: "Macro scrub, cream, and tactile swipes.",
      prompt:
        "Extreme close-up macro photography of [INGREDIENT/TEXTURE] — e.g. coffee grounds, shea butter, vitamin C crystals, creamy body-care texture, tactile swipes. Warm studio light, soft shadows, high detail, editorial beauty feel. Delicious but skin-care appropriate. 4K, photorealistic."
    },
    {
      key: "retail-mock",
      label: "🏪 Retail Mock",
      description: "Packaging, shelf, display, and type exploration.",
      prompt:
        "Realistic retail shelf or branded display mock for Frank Body [PRODUCT NAME]. Pharmacy or beauty retailer environment — e.g. Chemist Warehouse, MECCA, Target. Correct shelf height, accurate product facings, packaging readable, brand block clear, campaign headline space, sharp typography."
    }
  ],
  exportPresets: [
    { key: "pdp", label: "PDP", size: "1600 x 2000", format: "PNG/JPG", media_types: ["image"] },
    { key: "email-hero", label: "Email hero", size: "2400 x 1350", format: "JPG", media_types: ["image"] },
    { key: "instagram-feed", label: "Instagram feed", size: "1080 x 1350", format: "JPG", media_types: ["image"] },
    { key: "instagram-story", label: "Instagram story", size: "1080 x 1920", format: "JPG", media_types: ["image"] },
    { key: "paid-social", label: "Paid social", size: "1200 x 628", format: "JPG", media_types: ["image"] },
    { key: "transparent-png", label: "Transparent PNG", size: "source", format: "PNG", media_types: ["image"] },
    { key: "high-res-master", label: "High-res master", size: "source/upscaled", format: "PNG/TIFF", media_types: ["image"] },
    { key: "video-storyboard", label: "Motion storyboard", size: "source loop", format: "GIF + JSON", media_types: ["video"] }
  ],
  voice: {
    appTitle: "The Art Dept.",
    labTitle: "Frank Body Image Studio",
    primaryAction: "Generate",
    emptyState: "Waiting for the brief...",
    approved: "Approved. Hot."
  }
};

export const defaultBrief = {
  title: "",
  productName: "",
  taskType: "background-replace",
  channel: "PDP",
  tone: "Cheeky but director-ready",
  prompt: "",
  negativePrompt: ""
};
