/**
 * The AutoSolutions OS chrome: the app switcher and the company switcher.
 *
 * VENDORED BY COPY — the canonical file lives in the core repo
 * (core/os-chrome/). Every app carries a byte-identical copy, so the menus a
 * person sees are the same in every app. Do not edit this file inside an app;
 * change the canonical copy, run core/sync-os-chrome.sh, and push each app.
 *
 * Everything rendered here comes from one core call (os_context), the app grid
 * is the hub's own design (taxonomy and 48px wordmark plates, artwork served
 * from the core), and switching company goes through switch_company_for_app():
 * the acting company changes server-side, then the browser is sent to THAT
 * company's deployment of the current app — a different front end when the
 * company runs its own — or to the hub when the new company does not own this
 * app. A full navigation, deliberately: everything below the sign-in
 * re-derives under the new company.
 */
import { useEffect, useRef, useState } from "react";
import "./os-chrome.css";

export type OsClient = {
  rpc: (fn: string, args?: Record<string, unknown>) => PromiseLike<{ data: unknown; error: { message: string } | null }>;
};

export type OsContext = {
  tenant: { id: string; slug: string; name: string; logoUrl: string | null; logoPlainUrl: string | null } | null;
  tenants: Array<{ id: string; slug: string; name: string; logoUrl: string | null; logoPlainUrl: string | null; osRole: string }>;
  apps: Array<{ key: string; name: string; iconUrl: string | null; url: string | null; sortOrder: number }>;
};

const HUB_URL = "https://autosolutions.app";
const LABELS = "https://allzlfxbemhhhihdpxfv.supabase.co/storage/v1/object/public/brand/app-labels/";

/* The hub's own taxonomy, verbatim — group / section / order are the design
   reference's, so the grid reads the same in every app. */
const COLUMNS: Array<{ group: string; sections: { title?: string; apps: string[] }[] }> = [
  {
    group: "Marketing",
    sections: [
      { title: "Revenue", apps: ["ad-management", "shopify-sales"] },
      { title: "Content & Social", apps: ["content-calendar", "social-simulator", "franks-kitchen"] },
    ],
  },
  {
    group: "",
    sections: [
      { title: "Content & Social", apps: ["shelf-simulator", "product-validator"] },
      { title: "Design", apps: ["design-studio"] },
    ],
  },
  {
    group: "Operations",
    sections: [
      { apps: ["label-maker", "asset-portal", "hub", "ops-hub"] },
      { title: "Sales", apps: ["growth-engine", "ecommerce-sales", "smart-leadgen-crm", "key-accounts"] },
    ],
  },
  {
    group: "Internal Comms",
    sections: [{ apps: ["smart-comms-hub"] }, { title: "People", apps: ["ai-interviewer"] }],
  },
];

const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

let cached: Promise<OsContext | null> | null = null;
function loadContext(client: OsClient): Promise<OsContext | null> {
  if (!cached) {
    cached = Promise.resolve(client.rpc("os_context"))
      .then(({ data, error }) => (error ? null : (data as OsContext)))
      .catch(() => null);
  }
  return cached;
}

function withTenant(url: string, slug: string | null): string {
  try {
    const u = new URL(url);
    if (slug) u.searchParams.set("tenant", slug);
    return u.toString();
  } catch {
    return url;
  }
}

function useOsContext(client: OsClient): OsContext | null {
  const [ctx, setCtx] = useState<OsContext | null>(null);
  useEffect(() => {
    let live = true;
    void loadContext(client).then((value) => { if (live) setCtx(value); });
    return () => { live = false; };
  }, [client]);
  return ctx;
}

function useDismiss(open: boolean, close: () => void, ref: React.RefObject<HTMLElement | null>) {
  useEffect(() => {
    if (!open) return;
    const onClick = (e: MouseEvent) => { if (ref.current && !ref.current.contains(e.target as Node)) close(); };
    const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") close(); };
    window.addEventListener("mousedown", onClick);
    window.addEventListener("keydown", onKey);
    return () => { window.removeEventListener("mousedown", onClick); window.removeEventListener("keydown", onKey); };
  }, [open, close, ref]);
}

type Entry = { designKey: string; name: string; url: string | null; current: boolean };

function Plate({ entry, tenantSlug, onOpen }: { entry: Entry; tenantSlug: string | null; onOpen?: () => void }) {
  const mark = (
    <img className="osx-label" src={LABELS + entry.designKey + "-label.png"} alt={entry.name}
      onError={(e) => { (e.target as HTMLImageElement).outerHTML = '<span class="osx-label-text">| ' + entry.name + "</span>"; }} />
  );
  if (!entry.url) {
    return <div className="osx-appplate is-disabled" aria-disabled="true" title="No deployment yet">{mark}</div>;
  }
  return (
    <a className={"osx-appplate" + (entry.current ? " is-current" : "")}
      href={withTenant(entry.url, tenantSlug)}
      {...(entry.current ? {} : { target: "_blank", rel: "noreferrer noopener" })}
      aria-label={"Open " + entry.name} onClick={onOpen}>
      {mark}
    </a>
  );
}

/** The app grid — the hub's design, identical in every app.
    variant="menu": one column, for a nav popover. variant="grid": four columns. */
export function OsAppSwitcher({ client, appKey, variant = "menu", onOpen }: {
  client: OsClient; appKey: string; variant?: "grid" | "menu"; onOpen?: () => void;
}) {
  const ctx = useOsContext(client);
  if (!ctx) return <p className="osx-empty">Loading…</p>;

  const tenantSlug = ctx.tenant?.slug ?? null;
  const byKey = new Map<string, { name: string; url: string | null; key: string }>();
  for (const app of ctx.apps) {
    byKey.set(slugify(app.key), app);
    byKey.set(slugify(app.name), app);
  }
  byKey.set("hub", { key: "hub", name: "Hub", url: HUB_URL });

  const placed = new Set<string>();
  const columns = COLUMNS.map((column) => ({
    group: column.group,
    sections: column.sections
      .map((section) => ({
        title: section.title,
        entries: section.apps
          .map((designKey) => {
            const app = byKey.get(designKey);
            if (!app) return null;
            placed.add(app.key);
            return { designKey, name: app.name, url: app.url, current: app.key === appKey || (designKey === "hub" && appKey === "hub") } as Entry;
          })
          .filter((entry): entry is Entry => entry !== null),
      }))
      .filter((section) => section.entries.length > 0),
  })).filter((column) => column.sections.length > 0);

  const rest = ctx.apps.filter((app) => !placed.has(app.key));
  if (rest.length > 0) {
    columns.push({
      group: "Other",
      sections: [{ title: undefined, entries: rest.map((app) => ({ designKey: slugify(app.key), name: app.name, url: app.url, current: app.key === appKey })) }],
    });
  }

  return (
    <div className={"osx-cols" + (variant === "menu" ? " osx-cols--menu" : "")}>
      {columns.map((column, columnIndex) => (
        <div key={column.group || "col-" + columnIndex}>
          <div className="osx-grp">{column.group || "\u00a0"}</div>
          {column.sections.map((section, sectionIndex) => (
            <div key={section.title ?? "sec-" + sectionIndex}>
              {section.title && <div className="osx-sec">{section.title}</div>}
              {section.entries.map((entry) => (
                <Plate key={entry.designKey} entry={entry} tenantSlug={tenantSlug} {...(onOpen ? { onOpen } : {})} />
              ))}
            </div>
          ))}
        </div>
      ))}
      {columns.length === 0 && (
        <p className="osx-empty">You are not entitled to any apps in this workspace. Ask your AutoSolutions administrator.</p>
      )}
    </div>
  );
}

/** App plate + popover, for apps whose shell has no nav slot of its own. */
export function OsAppSwitcherPlate({ client, appKey }: { client: OsClient; appKey: string }) {
  const ctx = useOsContext(client);
  const [open, setOpen] = useState(false);
  const root = useRef<HTMLDivElement>(null);
  useDismiss(open, () => setOpen(false), root);
  if (!ctx) return null;
  const current = ctx.apps.find((a) => a.key === appKey);
  return (
    <div className="osx-root" ref={root}>
      <button type="button" className="osx-plate" onClick={() => setOpen(!open)} aria-haspopup="true" aria-expanded={open}>
        <span className="osx-pipe" aria-hidden="true" />
        <span className="osx-plate__name">{current?.name ?? (appKey === "hub" ? "Hub" : appKey)}</span>
        <span className="osx-chevron" aria-hidden="true" />
      </button>
      {open && (
        <div className="osx-menu" role="menu">
          <OsAppSwitcher client={client} appKey={appKey} variant="menu" onOpen={() => setOpen(false)} />
        </div>
      )}
    </div>
  );
}

/** The company switcher — identical in every app. Switching lands on the new
    company's own deployment of this app, or the hub when it has none. */
export function OsCompanySwitcher({ client, appKey }: { client: OsClient; appKey: string }) {
  const ctx = useOsContext(client);
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const root = useRef<HTMLDivElement>(null);
  useDismiss(open, () => setOpen(false), root);
  if (!ctx || !ctx.tenant) return null;

  const single = ctx.tenants.length <= 1;
  const mark = ctx.tenant.logoPlainUrl ?? ctx.tenant.logoUrl;

  const choose = async (tenantId: string) => {
    if (busy || tenantId === ctx.tenant!.id) { setOpen(false); return; }
    setBusy(true);
    const { data, error } = await client.rpc("switch_company_for_app", {
      t: tenantId, app_key: appKey === "hub" ? null : appKey,
    });
    if (error) { setBusy(false); return; }
    const result = (data ?? {}) as { appUrl?: string | null; tenantSlug?: string | null };
    if (appKey === "hub") { window.location.assign(HUB_URL); return; }
    window.location.assign(result.appUrl ? withTenant(result.appUrl, result.tenantSlug ?? null) : HUB_URL);
  };

  return (
    <div className="osx-root" ref={root}>
      <button type="button" className={"osx-plate osx-plate--company" + (single ? " is-static" : "")}
        onClick={() => !single && setOpen(!open)} aria-haspopup={!single} aria-expanded={open}
        aria-label={"Company: " + ctx.tenant.name + (single ? "" : ". Switch company")}>
        {mark ? <img className="osx-plate__mark" src={mark} alt={ctx.tenant.name} /> : <span className="osx-plate__name">{ctx.tenant.name}</span>}
        {!single && <span className="osx-chevron" aria-hidden="true" />}
      </button>
      {open && (
        <div className="osx-menu osx-menu--right" role="menu">
          <span className="osx-menu__label">Your companies</span>
          {ctx.tenants.map((t) => {
            const isCurrent = t.id === ctx.tenant!.id;
            const m = t.logoPlainUrl ?? t.logoUrl;
            return (
              <button key={t.id} type="button" role="menuitem" disabled={busy}
                className={"osx-item" + (isCurrent ? " is-current" : "")}
                onClick={() => void choose(t.id)}>
                {m ? <img className="osx-item__mark" src={m} alt="" /> : <span className="osx-pipe" aria-hidden="true" />}
                <span className="osx-item__name">{t.name}</span>
                {isCurrent && <span className="osx-check" aria-hidden="true" />}
              </button>
            );
          })}
          {busy && <span className="osx-menu__label">Switching…</span>}
        </div>
      )}
    </div>
  );
}

/** A slim OS bar for apps with no top chrome of their own (e.g. Label Maker). */
export function OsBar({ client, appKey }: { client: OsClient; appKey: string }) {
  return (
    <div className="osx-bar">
      <OsAppSwitcherPlate client={client} appKey={appKey} />
      <span className="osx-bar__spacer" />
      <OsCompanySwitcher client={client} appKey={appKey} />
    </div>
  );
}
